id: I56623C53
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:01:45+00:00'
last_modified: '2022-06-08T12:40:57.687882+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18584
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    1AFD:
      image_group_id: I1KG18738
      title: Volume 1 of bas mtha'i smre sngags/
      total_pages: 86
      order: 1
      base_file: 1AFD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
