id: P006936
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18584
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  volumes:
    f9238f08210b4076806d09465bca522c:
      image_group_id: I1KG18738
      title: Volume 1 of bas mtha'i smre sngags/
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
ebook_metadata:
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  sku: P006936
  cover: cover.jpg
  layers:
  - pagination
