id: P006936
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:41.618194
source_metadata:
  id: bdr:W1KG18584
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  volumes:
    f9238f08210b4076806d09465bca522c:
      image_group_id: I1KG18738
      title: Volume 1 of bas mtha'i smre sngags/
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
