id: P006936
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18584
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  volumes:
    2c3fc1082048489f82dba1c725feec50:
      image_group_id: I1KG18738
      title: ''
      volume_number: 1
      total_pages: 86
ebook_metadata:
  title: བས་མཐའི་སྨྲེ་སྔགས།
  author: ''
  sku: P006936
  cover: cover.jpg
  layers:
  - pagination
